### ISSUE TITLE
to manny error 

### ISSUE THREAD

**Issue by Hjgaming** [GhostyORG/GhostyBotList#1]

**Comment by Hjgaming** [comment]
one by one error i fill all config

**Comment by killerclaws12** [comment]
Gives errors because it's still in development.

**Comment by SpaceLeft** [comment]
![Capture](https://user-images.githubusercontent.com/40790870/199685932-1d799a89-2c73-4cf1-bc97-5ea767419376.PNG)

**Comment by SpaceLeft** [comment]
+ forgot upload files ejs 
![Capture](https://user-images.githubusercontent.com/40790870/199686933-8aaef494-1d09-47e2-8bfe-3e486752b45b.PNG)
